---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yml
  - secrets.yml
  - clusterinstance.yml
  - day2/99-worker-mytest-mcp.yml

generatorOptions:
  disableNameSuffixHash: true
