apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
    name: ocp2-upgrade
placementBindingDefaults:
    name: ocp2-upgrade-placement-binding
policyDefaults:
    namespace: ztp-upgrade
    placement:
        labelSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - ocp2
    remediationAction: inform
    severity: low
    namespaceSelector:
        exclude:
            - kube-*
        include:
            - '*'
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
policies:
    - name: ocp2-upgrade-platform-upgrade
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "100"
      manifests:
        - path: ClusterVersion.yml 
          patches:
            - metadata:
                name: version
              spec:
                channel: stable-4.18
                desiredUpdate:
                    version: 4.18.17
                upstream: https://api.openshift.com/api/upgrades_info/v1/graph
              status:
                history:
                    - state: Completed
                      version: 4.18.17
    - name: ocp2-upgrade-platform-upgrade-prep
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: "1"
      manifests:
        - path: ImageSignature.yml 
          patches:
            - metadata:
                name: release-image-signature
              binaryData: 
                  sha256-9d24a8cdd67b8f18c99547d5910e4863e7aab5bd888e26670a00dbda0a9d4687: owGbwMvMwMEoOU9/4l9n2UDG0wf6khgyHGc7VSslF2WWZCYn5ihZKVQrZeYmpqeCWSn5ydmpRbq5iXmZaanFJbopmelACiilVJyRaGRqZmWZYmSSaJGckmJmnmSRZmiRbGlpamKeYmppaJBqYmFmnGqemJhkmpRiYWGRamRmZm6QaGCQkpSSaJBomWJiZmGuVKujoFRSWQCyTimxJD83M1khOT+vJDEzL7VIoTgzPS+xpLQoVQmoKjMlNa8ks6QS2WFFqWmpRal5yWDthaWJlXqZ+fr5Bal5xRmZaSVA6ZzUxOJU3ZTUMv385AIY38pEz9BCz9Bct8LCLN7MRKkW5Ij8gpLM/DxoCCQXpQIdUwQyNSg1RcEjsUTBH2hqMMhUhWCgqzLz0hUcS0sy8oHhVqlgoGegZwg0ppNJhoWBkYOBjZUJFKwMXJwCsMDON+L/H/jwv1CS/nR3S/eMPezWhZduCd05E6S0+BSbWYHo5ZyNlqnb/nc8O/vx9sQrbbenqT/WLqy10o1e7PbaUrRs9qGcS2Kmoo+m1Hy58ytb+OFBvZmpO06XTkkTa/tmdOq66iqBtHmF/zXkji1/EvjzwIofKVar77dJztH0EL7Rcvpv1qrg1kksDiHz2Vd0bH2S/mbPzSm6c+cFHTjjXr27/KEYbwH/nKCXLM6sdu0rjIwZnXfNmvv38yqrWYl3fjz//vH93GeWDSFGFkeey2QkF5xMW9kV3DzR7GOs5KKLlgyVHCrdNbuaQjmarC+6V/CuvHeFL3ThBYVLCr+PWuh+r2n9aZ2aOLOr6pT+o7V97vs3e0TfC13Eyx9q+NVtvuka4fw5e/X57derFj25y/rilEpBR4LE1Lpr1v92SC9yXTnLqrLlVvBHPwd7pzmP91d/ZX2qemNm/I95Vwvkj/dqaby99drL3tdZkZmjwKAvTq3Ba4lK/6qLRe+al/gotMlHR6Ve05WJe9ol/vb4K76Zi/nPnFbf/XKZ+od7p+ZYd8Zuc1zVrtDqs1p8U6zXc6O9l7Num779kTtDQHou19cX7gs8Mu7Ert0rdnFFkEWaVv/NgBQ2cVXN6eqxN0QnsR26qNsT5ZXN9dNUsbYsWfXLdGPPpQf1pA0vL2FSSvMw2rdpQt9eQVHhF7KtvzsWNMp+uHK2Mm7HGc66Sx8XAAA=
        - path: DisconnectedICSP.yml
          patches:
            - metadata:
                name: disconnected-internal-icsp
              spec:
                repositoryDigestMirrors: 
                    - mirrors:
                        - bastion.ocp.pdlab.sg:8443/openshift-release-dev
                      source: quay.io/openshift-release-dev
