apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    ran.openshift.io/ztp-deploy-wave: "100"
spec:
  channel: stable-4.17
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
