apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-create-testfile
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/ztp-day2-success
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8;base64,U3VjY2Vzc2Z1bGx5IGFwcGxpZWQgdGVzdCBGaWxlIGZyb20gWlRQIERheS0yIQo=
